# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/xaga/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),xaga)

$(call add-radio-file-sha1-checked,radio/apusys.img,471b2b3cf1202be19a24dfc369511e4720e53202)
$(call add-radio-file-sha1-checked,radio/audio_dsp.img,3b558bacf85cc400bce2219bd764d9d14cec5fdc)
$(call add-radio-file-sha1-checked,radio/ccu.img,f2089551d050dcc8d00e7db41a1a11d18c2c6c31)
$(call add-radio-file-sha1-checked,radio/dpm.img,07368a6011ac8c8878272079e537b305267c8932)
$(call add-radio-file-sha1-checked,radio/dtbo.img,a4ef745f1120344b77416c7573cc1b56d5cc47d6)
$(call add-radio-file-sha1-checked,radio/gpueb.img,6615571b2e69455059eeb6b4b7f6b07bab3a9d93)
$(call add-radio-file-sha1-checked,radio/gz.img,31728da3191aaa4efaf588087f025ef53762fb9b)
$(call add-radio-file-sha1-checked,radio/lk.img,cfac28aa2356b77c1bec670a3a46538674c59100)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,a487e587c9c3a28775210d8ab61b7b119b3e2e54)
$(call add-radio-file-sha1-checked,radio/mcupm.img,b4f25cd66a7f0cce97ea149b5f0777cae907821b)
$(call add-radio-file-sha1-checked,radio/md1img.img,04de757ccefe12dc0d90ddc8468463e4543471c0)
$(call add-radio-file-sha1-checked,radio/mvpu_algo.img,c4c168859ce95b81fd7c9ec3edca18a9e11570cf)
$(call add-radio-file-sha1-checked,radio/pi_img.img,153dd7c40ea7146d05a50002caa9e60640639c08)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,d9399d4faeea64cf82b2675aa6b26bd8cbd75e36)
$(call add-radio-file-sha1-checked,radio/scp.img,d11f4fcf26d39474a614dd82f3d74f2836ebdf53)
$(call add-radio-file-sha1-checked,radio/spmfw.img,cb270fd6663dc340c441a8103f6c44e4bdb2bf5f)
$(call add-radio-file-sha1-checked,radio/sspm.img,4cf3288d4e82a09e82c0f621a6d2925c9c86355b)
$(call add-radio-file-sha1-checked,radio/tee.img,3280414ea1fd5f3ed1537fd129459651e33d5b82)
$(call add-radio-file-sha1-checked,radio/vcp.img,612efe2c529cc568ff1694d6c21ccd5364f67051)

endif
